version: "3.7"

services:
  youtube-bot:
    build: .
    entrypoint: python bot.py
    volumes:
    - .:/usr/src/server/
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
    - 5432:5432
  celery:
    build: .
    command: celery -A celery worker -l info
    volumes:
      - .:/usr/src/server/
    env_file:
      - .env
    depends_on:
      - redis
      - db
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
volumes:
  postgres_data: