version: "3.7"

services:
  youtube-bot:
    build: .
    entrypoint: python bot.py
    volumes:
    - .:/usr/src/server/
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
    - 5432:5432
volumes:
  postgres_data: